<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\OpenOrders;

class OpenOrdersData extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231701,
            'OrderDate' => '2023-05-15',
            'FirstName' => "Rose",
            'LastName' => "Wild",
            'Address' => "919 Wild Rose Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Douglasville",
            'ShipState' => "GA",
            'Zipcode' => "30134",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402317,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231702,
            'OrderDate' => '2023-05-15',
            'FirstName' => "Rosie",
            'LastName' => "Wildered",
            'Address' => "4927 Goodwin Avenue",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Post Falls",
            'ShipState' => "Washington",
            'Zipcode' => "83854",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402318,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231703,
            'OrderDate' => '2023-04-22',
            'FirstName' => "Rosa",
            'LastName' => "Wid",
            'Address' => "4323 Green Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Nashville",
            'ShipState' => "Tennessee",
            'Zipcode' => "37222",
            'Country' => "US",
            'LocalStatus' => "Bad Address",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402319,
            'Type' => "H"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231704,
            'OrderDate' => '2023-05-11',
            'FirstName' => "Rhea",
            'LastName' => "Wilda",
            'Address' => "3176 Davis Court",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Collinsville",
            'ShipState' => "Illinois",
            'Zipcode' => "62234",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402320,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231705,
            'OrderDate' => '2023-05-13',
            'FirstName' => "Janna",
            'LastName' => "Manar",
            'Address' => "3440 May Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Ashland",
            'ShipState' => "Kentucky",
            'Zipcode' => "44134",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402321,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231706,
            'OrderDate' => '2023-04-23',
            'FirstName' => "Shie",
            'LastName' => "Laan",
            'Address' => "2886 Garrett Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Eagleville",
            'ShipState' => "Pennsylvania",
            'Zipcode' => "30884",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402322,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231707,
            'OrderDate' => '2023-05-15',
            'FirstName' => "Rimna",
            'LastName' => "Edab",
            'Address' => "2195 Tecumsah Lane",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Cedar Falls",
            'ShipState' => "Pennsylvania",
            'Zipcode' => "30888",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402323,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231708,
            'OrderDate' => '2023-04-27',
            'FirstName' => "Ando",
            'LastName' => "Park",
            'Address' => "654 Wexford Way",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Augusta",
            'ShipState' => "South Carolina",
            'Zipcode' => "97134",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402324,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231709,
            'OrderDate' => '2023-04-28',
            'FirstName' => "Sandy",
            'LastName' => "Dara",
            'Address' => "1327 Roosevelt Road",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Moundridge",
            'ShipState' => "Kansas",
            'Zipcode' => "67107",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402315,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231710,
            'OrderDate' => '2023-04-27',
            'FirstName' => "Tonya",
            'LastName' => "Cal",
            'Address' => "2867 Simpson Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Bloomington",
            'ShipState' => "Illinois",
            'Zipcode' => "44134",
            'Country' => "US",
            'LocalStatus' => "Bad Address",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402326,
            'Type' => "H"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231722,
            'OrderDate' => '2023-05-04',
            'FirstName' => "Calla",
            'LastName' => "Merand",
            'Address' => "261 Ocello Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "San Diego",
            'ShipState' => "California",
            'Zipcode' => "899434",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402327,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231704,
            'OrderDate' => '2023-04-22',
            'FirstName' => "Joko",
            'LastName' => "Lafu",
            'Address' => "3746 Reynolds Alley",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Burbank",
            'ShipState' => "California",
            'Zipcode' => "663598",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402328,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231713,
            'OrderDate' => '2023-05-8',
            'FirstName' => "Daisy",
            'LastName' => "Hadid",
            'Address' => "4537 Tree Top Lane",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Philadelphia",
            'ShipState' => "Pennsylvania",
            'Zipcode' => "500134",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402329,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231714,
            'OrderDate' => '2023-05-10',
            'FirstName' => "Cheyyan",
            'LastName' => "Obesso",
            'Address' => "261 Ocello Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "San Diego",
            'ShipState' => "California",
            'Zipcode' => "20134",
            'Country' => "US",
            'LocalStatus' => "Bad Address",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402330,
            'Type' => "H"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231715,
            'OrderDate' => '2023-05-8',
            'FirstName' => "Randall",
            'LastName' => "Dally",
            'Address' => "229 Heavner Court",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Garden City",
            'ShipState' => "New York",
            'Zipcode' => "21530",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402331,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231716,
            'OrderDate' => '2023-05-9',
            'FirstName' => "Dolly",
            'LastName' => "Plazad",
            'Address' => "652 Hidden Valley Road",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Waterford",
            'ShipState' => "California",
            'Zipcode' => "95386",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402332,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231717,
            'OrderDate' => '2023-05-14',
            'FirstName' => "Eddie",
            'LastName' => "Smander",
            'Address' => "1921 Airplane Avenue",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Windsor",
            'ShipState' => "Connecticut",
            'Zipcode' => "06095",
            'Country' => "US",
            'LocalStatus' => "Bad Address",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402333,
            'Type' => "H"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231718,
            'OrderDate' => '2023-05-15',
            'FirstName' => "Cathy",
            'LastName' => "Bando",
            'Address' => "2052 Liberty Street",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Dallas",
            'ShipState' => "Texas",
            'Zipcode' => "75204",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402334,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231719,
            'OrderDate' => '2023-05-9',
            'FirstName' => "Liayan",
            'LastName' => "Rofan",
            'Address' => "226 Walnut Hill Drive",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Cincinnati",
            'ShipState' => "Ohio",
            'Zipcode' => "45217",
            'Country' => "US",
            'LocalStatus' => "",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402335,
            'Type' => "O"
        ]);
        OpenOrders::create([
            'RunDate' => date('Y-m-d H:i:s'),
            'StoreID' => 999723,
            'StoreName' => 'The Company ABC',
            'OrderNumber' => 231720,
            'OrderDate' => '2023-05-7',
            'FirstName' => "Rimanda",
            'LastName' => "Socorro",
            'Address' => "2198 Mudlick Road",
            'Address2' => "",
            'Address3' => "",
            'ShipCity' => "Glen Carbon",
            'ShipState' => "Illinois",
            'Zipcode' => "62034",
            'Country' => "US",
            'LocalStatus' => "Bad Address",
            'OnlineStatus' => "processing",
            'Source' => NULL,
            'OrderID' => 1000402336,
            'Type' => "H"
        ]
        );
    }
}
